---
- hosts: all
  tasks:
    - systemd: name={{item}} state=stopped
      with_items:
        - mongos
        - mongoc
        - mongod-mongo1
        - mongod-mongo2
        - mongod-mongo3
        - mongod-mongo4
      ignore_errors: yes
    - file: path=/data state=absent

